{% set name = "google-colab" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google-colab-{{ version }}.tar.gz
  sha256: 932fd05e649dba27457ef9959bc5f3b1e6f7c8d9b4451c9fa1b4d2eb0c3fa3ab
  patches: 
    - setup.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - google-auth
    - ipykernel
    - ipython
    - notebook
    - pandas
    - portpicker
    - python >={{ python_min }}
    - requests
    - six
    - tornado

test:
  imports:
    - google
    - google.colab
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://colab.research.google.com/
  license: Apache-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'Python libraries for Google Colaboratory'
  description: |
    Colaboratory is a research project created to help disseminate machine 
    learning education and research. It’s a Jupyter notebook environment 
    that requires no setup to use. For more information, see our FAQ.
  doc_url: https://colab.research.google.com/
  dev_url: https://github.com/googlecolab/colabtools

extra:
  recipe-maintainers:
    - jan-janssen
